# To create the environment:
# conda env create -f conda-env.yml
# Postgres must be already installed and running

# Notes for mac:
# DYLD_FALLBACK_LIBRARY_PATH=/Users/esuli/anaconda/envs/ics/lib/
# When using postgres.app the bin dir must be added to the path:
# export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
# To run the code a symbolic link may be needed:
# ln -s libgcc_s.10.5.dylib libgcc_s.1.dylib

name: ics
dependencies:
- cherrypy
- cython
- mako
- markupsafe
- numpy
- pip
- python
- scikit-learn
- scipy
- setuptools
- sqlalchemy
- wheel
- pip:
  - psycopg2
