# To create the environment:
# conda env create -f conda-env.yml
# Postgres must be already installed and running

# Notes for mac:
# DYLD_FALLBACK_LIBRARY_PATH=/Users/esuli/anaconda/envs/ics/lib/
# When using postgres.app the bin dir must be added to the path:
# export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
# To run the code a symbolic link may be needed:
# ln -s libgcc_s.10.5.dylib libgcc_s.1.dylib

name: ics
dependencies:
- cherrypy=3.8.0=py35_0
- cython=0.25.2=py35_0
- mako=1.0.6=py35_0
- markupsafe=0.23=py35_2
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pip=9.0.1=py35_1
- python=3.5.2=0
- readline=6.2=2
- scikit-learn=0.18.1=np111py35_0
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- sqlalchemy=1.1.4=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - psycopg2==2.6.2
